<a href="https://colab.research.google.com/github/edusalman345/numpy/blob/main/Manuplating_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import

In [1]:
import numpy as np

Data

In [86]:
marks = np.array([
    [78, 85, 90],
    [45, 50, 40],
    [88, 92, 84],
    [60, 65, 58],
    [95, 98, 100]
])

Calculating Average marks per student

In [45]:
avg_per_student = np.mean(marks, axis=1)

In [50]:
print('Average marks per student:')
for index, x in enumerate(avg_per_student, start=1):
    print(f"Student{index} = {round(x,2)}")

Average marks per student:
Student1 = 84.33
Student2 = 45.0
Student3 = 88.0
Student4 = 61.0
Student5 = 97.67


Calculating Average marks per subject

In [44]:
avg_per_subject = np.mean(marks, axis=0)

In [41]:
print('Average marks per subject:')
for index, x in enumerate(avg_per_subject, start=1):
    print(f"Subject{index} = {round(x,2)}")

Average marks per subject:
Subject1 = 73.2
Subject2 = 78.0
Subject3 = 74.4


In [56]:
print("Total Per Student Marks:")
student_marks = np.sum(marks, axis=1)
for index, x in enumerate(student_marks, start=1):
    print(f"Student{index} = {x}")

Total Per Student Marks:
Student1 = 253
Student2 = 135
Student3 = 264
Student4 = 183
Student5 = 293


Calculating Highest Marks

In [59]:
max_marks = student_marks.max()
student_index = np.where(student_marks == max_marks)
print(f"Topper: Student{student_index[0][0]+1} with {max_marks}")

Topper: Student5 with 293


Calculating Lowest Marks

In [60]:
min_marks = student_marks.min()
student_index = np.where(student_marks == min_marks)
print(f"Lowest Marks: Student{student_index[0][0]+1} with {min_marks}")


Lowest Marks: Student2 with 135


Calculating Who passed > 70

In [66]:
passed_sudents = np.where(avg_per_student > 70)
print("Passed Students:")
for index in passed_sudents[0]:
    print(f"Student{index+1}")

print(passed_sudents)

Passed Students:
Student1
Student3
Student5
(array([0, 2, 4]),)


Calculating Who Failed < 50

In [67]:
failled_students = np.where(marks < 50)
print("Failled Students:")
for index in failled_students[0]:
    print(f"Student{index+1}")

Failled Students:
Student2
Student2


Bonous Marks (5)

In [87]:
print('Before')
for x in marks:
  print(x)
print('After')
bonous_marks = 5
for i in range(len(marks)):
  for j in range(len(marks[i])):
    if marks[i][j] + bonous_marks <=100:
      marks[i][j] = marks[i][j] + bonous_marks
    elif marks[i][j] + bonous_marks > 100:
      marks[i][j] = 100

for x in marks:
  print(x)

Before
[78 85 90]
[45 50 40]
[88 92 84]
[60 65 58]
[ 95  98 100]
After
[83 90 95]
[50 55 45]
[93 97 89]
[65 70 63]
[100 100 100]


In [76]:
print(f"Before{marks}")
print(f"After{after_bonous}")

Before[[ 78  85  90]
 [ 45  50  40]
 [ 88  92  84]
 [ 60  65  58]
 [ 95  98 100]]
After[[ 83  90  95]
 [ 50  55  45]
 [ 93  97  89]
 [ 65  70  63]
 [100 103 105]]
