<a href="https://colab.research.google.com/github/edusalman345/numpy/blob/main/Numpy_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3,4,5])

In [5]:
print(arr1)

[1 2 3 4 5]


In [12]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [13]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr3= np.zeros((9,4))
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arr4 = np.identity(5)
arr4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
arr9 = np.array([[[1,2],[2,3]],[[3,4],[34,5]]])

In [25]:
arr9

array([[[ 1,  2],
        [ 2,  3]],

       [[ 3,  4],
        [34,  5]]])

In [21]:
arr9.shape

(2, 2, 2)

In [22]:
arr9.size

8

In [26]:
arr9.ndim

3

In [27]:
arr = np.array([5,10,15,20])

In [28]:
arr + 5

array([10, 15, 20, 25])

In [29]:
arr * 2

array([10, 20, 30, 40])

In [30]:
arr[arr>15]

array([20])